# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GodokChatting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GodokChatting
	pod 'Alamofire', '~> 5.0.0-beta.5'
	pod 'RxCocoa', '~> 5'
	pod 'RxSwift', '~> 5'
	pod 'SnapKit', '~> 5.0.0'
	pod 'SwiftlyIndicator'
	pod 'Then'
  pod 'Kingfisher', '~> 5.0'

end
